---
kind: pipeline
type: docker
name: default

steps:
- name: install and run scripts
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py install

- name: develop
  image: python:3.8
  commands:
  - python setup.py develop

- name: generate sdist
  image: python:3.8
  commands:
  - git fetch --tags
  - python setup.py sdist

- name: upload to pypi
  image: plugins/pypi
  when:
      event: tag
  settings:
    skip_build: True
    username: dessia_tech
    password:
        from_secret: pypi_password

- name: create dist
  image: python:3.8
  commands:
  - pip install wheel
  - python setup.py sdist bdist_wheel


- name: upload doc master
  image: appleboy/drone-scp
  when: 
    branch: 
      - master
  settings:
    host: austerlitz.dessia.tech
    target: /var/www/documentation/dessia_api_client/
    source: doc/build/html/*
    strip_components: 3
    username: drone
    password:
      from_secret: ssh_drone_password


- name: notify
  when:
    status:
    - failure
  image: drillster/drone-email
  settings:
    host: mail.dessia.tech
    username: technical@dessia.tech
    password:
     from_secret: email_password
    from: technical@dessia.tech
    recipients: [ root@dessia.tech ]
